<a href="https://colab.research.google.com/github/cristiane88/ShePY/blob/main/Aula_4_ShePY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 4 - ShePY
## NumPY - Numerical Python

NumPY é uma poderosa biblioteca que suporta arrays e matrizes e muito importante para processamento numerico em Python. Esses tipos de cálculos númericos são amplamente utilizados em tarefas como: Modelos de Machine Learning, Visão computacional e tarefas matemáticas.

Alguns recursos no Numpy?
- ndarray: um array multidimensional eficaz que oferece operações rápidas.
- funções matemáticas para operações rápidas em arrays de dados, sem que haja a necessidade de escrever laços.

### Criando arrays com Numpy:

### Uma Dimensão - Linear

In [ ]:
import numpy as np

In [ ]:
# Criando um array a partir de uma lista
mylist = [1, 2, 3]
myarray = np.array(mylist)
myarray

array([1, 2, 3])

In [ ]:
type(myarray)

numpy.ndarray

In [ ]:
myarray = np.array([1, 2, 3])
myarray

array([1, 2, 3])

In [ ]:
# Criando um  array com arange, sendo o intervalo de 0 a 10.
ald = np.arange(0, 10)
ald

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Criando um array de zeros.
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [ ]:
array = np.array(['pyton', 'R', 'Java'])
array

array(['pyton', 'R', 'Java'], dtype='<U5')

###Arrays de 2 dimensões

In [ ]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
zeros2d = np.zeros(shape=(3, 4)) # 3 linhas e 4 colunas
zeros2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Array de 3 dimensões

In [ ]:
array3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12]], [[13, 14, 15]]])
array3d

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), list([[10, 11, 12]]),
       list([[13, 14, 15]])], dtype=object)

Comparação de performace do Numpy

In [ ]:
idades = np.random.randint(50, size=1000)
idades

array([14, 14, 44, 48, 37, 44,  6, 43,  8, 14, 21, 34, 28,  8,  2, 37,  8,
        1, 45, 21, 17, 38,  6,  5, 48, 26, 32, 48, 19, 40, 25,  0, 28,  3,
       37, 18, 24,  8, 42, 18, 38, 19, 37, 19,  8, 13, 40, 48, 18, 28, 22,
       34,  1, 14, 24, 34, 16,  5, 18, 38, 31, 17, 32, 35, 12, 30, 11, 28,
        1, 20, 15,  7,  1, 14, 18, 34, 16, 46, 36, 29,  5, 34, 25, 32, 20,
       34, 15, 38, 45, 43, 42, 38, 23, 30,  4, 47,  4,  8, 44, 21, 18, 12,
       24,  2,  9, 25,  2, 39, 49, 36, 13, 21, 18, 25, 48,  3, 18, 47, 40,
       33, 16, 10, 34, 28, 32, 41, 45,  4, 47, 28,  0,  1, 45, 42, 48, 43,
       10, 14, 13, 29, 13, 15, 48, 48, 22, 39, 26, 40, 18, 17, 17, 39, 32,
       47, 10, 20,  0, 16, 22, 12, 24,  2, 32, 36,  4, 13, 28,  1, 36,  2,
        9, 48, 10, 12, 16,  5, 36, 24,  8,  1, 17, 26, 44, 31, 43, 30, 32,
       25, 28, 25, 48,  2, 45, 12, 39, 36, 48, 45, 35, 20,  3, 11, 13, 40,
       10, 19,  8,  9,  9, 10,  0, 14, 49, 22, 37, 29,  6, 42, 20, 43, 48,
       31,  8, 32, 43, 33

In [ ]:
idades = np.random.randint(50, size=1000)
len(idades)

1000

In [ ]:
%timeit sum(idades)

10000 loops, best of 5: 160 µs per loop


In [ ]:
%timeit np.sum(idades)

The slowest run took 61.00 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 5.39 µs per loop
